server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/volunteer_db
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true

